// Auto-generated from i18n-config.json
// Do not edit this file directly

export const defaultNodeTypeMap: Record<string, string> = {
  h1: 'Title',
  h2: 'Title',
  h3: 'Title',
  h4: 'Title',
  h5: 'Title',
  h6: 'Title',
  p: 'Subtitle',
  div: 'Text',
  span: 'Text',
  Fragment: 'Text',
};

export const defaultNodeType = 'Text';
