// Auto-generated from i18n-config.json
// Do not edit this file directly

export const defaultParsingConfig = {
  components: {
    Combobox: {
      props: ['placeholder', 'searchPlaceholder', 'emptyText'],
    },
    ClipboardButton: {
      props: ['tooltipCopy', 'tooltipCopied'],
    },
    TooltipContent: {
      textChild: true,
    },
    InstallButton: {
      textChild: true,
    },
  },
  ignoreProps: ['className', 'variant', 'id', 'key', 'style'],
};
